### ISSUE TITLE
features/nfs: wrong handling of nfs version

### ISSUE THREAD

**Issue by nowack73** [quattor/template-library-grid#101]
Hi,

in e.g. features/nfs/client/autofs.pan (lines 51-59), the handling of nfsversion does not work for SL 6. In SL 6, the default nfs version is 4, but the template assumes that the default is 3 (as it was in SL 4 and 5).

Best regards,
  Andreas

**Comment by jouvin** [comment]
I'll try to have a look in the remaining days (hours!) before 15.4...

**Comment by jouvin** [comment]
#142 should fix the problem. As SL5 is no longer used on WNs, I decided not take care of SL5 syntax which is a bit different from the SL6+. The main change is that if the version is specified in the Quattor configuration, it is set explicitely in the autofs config, whatever is the default version.

Not really tested but should work... @nowack73 any chance you could give it a try or at least comment the proposed fix before 15.4 release (very soon!).
