### ISSUE TITLE
WLCG repository name

### ISSUE THREAD

**Issue by Pansanel** [quattor/template-library-grid#118]
Hi,

In the repository/config/grid.pan, the repository name for WLCG is set to wlcg_x86_64 and only available for sl6. However, a SL5 version is also available:
* http://linuxsoft.cern.ch/wlcg/sl5/x86_64/
* http://linuxsoft.cern.ch/wlcg/sl6/x86_64/

Should we not use the following repo name:
`REPOSITORY_WLCG ?= 'wlcg_' + OS_VERSION_PARAMS['major'] + '_' + PKG_ARCH_DEFAULT;`
and later:
`SELF[length(SELF)] = REPOSITORY_WLCG;`

(in fact, each repository name should be set by the site).

**Comment by jouvin** [comment]
@Pansanel Looks sensible, I'll see if I can do it before 15.4... or feel free to open a PR with your suggestion.

**Comment by Pansanel** [comment]
Ok, I will propose a PR on Wednesday.

**Comment by Pansanel** [comment]
See https://github.com/quattor/template-library-grid/pull/140
