### ISSUE TITLE
(quattor-14.10) umd3 dpm problem for dpm-disk without xrootd

### ISSUE THREAD

**Issue by pigay** [quattor/template-library-grid#124]
Hi,

We encountered a problem with our dpm-disk servers when upgrading to recent packages (dpm-1.8.9).

For some reason, DPM certs directory `/etc/grid-security/dpmmgr/` is not created. We suspect that this is because we don't have xrootd protocol enabled on our SE.

This directory was present on our SE head node, maybe because of a previous configuration.

It resulted in "no space left on device" errors when putting a file on the SE.

Manually copying host cert in `/etc/grid-security/dpmmgr/dpmcert.pem` and `/etc/grid-security/dpmmgr/dpmkey.pem` solved the problem:
```
mkdir -p /etc/grid-security/dpmmgr/
cp /etc/grid-security/hostcert.pem /etc/grid-security/dpmmgr/dpmcert.pem
cp /etc/grid-security/hostkey.pem /etc/grid-security/dpmmgr/dpmkey.pem
chown -R dpmmgr:dpmmgr /etc/grid-security/dpmmgr/
```

Regards,

Pierre

**Comment by jouvin** [comment]
@pigay thanks for the report, I'll look at it and see if a fix can go into the 14.12 version about to be released.

**Comment by jouvin** [comment]
I confirm the issue: due to a mistake, at some point the code to create this DPM copy of the host certificate was removed from DPM and left only in xrootd. We probably missed it because many sites (this is basically required for WLCG sites) have xrootd configured.
I do my best to fix it quickly.

**Comment by jouvin** [comment]
@pigay the fix is available, I'd appreciate if you can test it (just copy the last version of the modified template in your configuration).

**Comment by pigay** [comment]
Dear @jouvin,

Thanks for the fix. I gave it a try and it looks fine.

I get the following in filecopy log:
```
2015/01/09-09:39:48 [INFO] Checking file /etc/grid-security/dpmmgr/dpmcert.pem...
2015/01/09-09:39:48 [INFO] Checking file /etc/grid-security/dpmmgr/dpmkey.pem...
```

Cheers,

Pierre
