### ISSUE TITLE
BDII plugin cannot read /etc/lrms/lcg-info-dynamic-maui.defaults

### ISSUE THREAD

**Issue by Pansanel** [quattor/template-library-grid#148]
The logs of the BDII on our CREAM CE is showing the following:
lcg-info-dynamic-maui: Error opening defaults file (/etc/lrms/lcg-info-dynamic-maui.defaults)
lcg-info-dynamic-maui: Exiting without output, GIP will use static values

**Comment by stdweird** [comment]
@Pansanel with #149 merged, can this be closed?

**Comment by Pansanel** [comment]
Yes, the issue can be closed.
