### ISSUE TITLE
Cleanup machine and job features templates

### ISSUE THREAD

**Issue by jrha** [quattor/template-library-grid#155]
Use of metaconfig etc. as discussed in #152.

**Comment by Pansanel** [comment]
The templates should also use the following tools:
https://gitlab.cern.ch/machinejobfeatures/mjf-scripts/blob/master/mjf.init

The /etc/machinefeatures should be dynamically created at boot time and/or update. It permits to remove the '''/etc/machinefeatures/shutdowmtime''' file, as if it exists, it prevents job to start (at least for the CMS VO).

**Comment by jrha** [comment]
@Pansanel do you have any time to look at solving this?
