### ISSUE TITLE
vo/functions.pan: is the removal of CVMFS mount points really correct?

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-grid#159]
Commit b4f30004bbcb7bc866fc54eb455161e3e0077479 introduced a change to directory created/configured as part of the VO configuration on UI and WN, removing the CVMFS mount points from the list. The commit message speaks only about the UI being affected by the change but it seems to affect also WNs and I am surprised that CVMFS can work without the mount point being created before (at least it has not always been the case). @Pansanel do you confirm that this change is find on newly installed WN?

**Comment by jrha** [comment]
@Pansanel ping?

**Comment by Pansanel** [comment]
Newly installed WN have the CVMFS directory. It is created by autofs.

**Comment by jrha** [comment]
Cool, closing this then.
@jouvin - feel free to reopen if you are not convinced, or have evidence that this is not the case.
