### ISSUE TITLE
GIP_CE_MAUI_PLUGIN_DEFAULTS_FILE owner/group

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-grid#174]
The owner and group of this file are set to root and 600 permissions in the template ce-maui-plugin-defaults.pan. I get a 'permission denied error' for the user ldap. 
Why not to set the permissions to 644 by default?

**Comment by Pansanel** [comment]
The issue has been fixed previously in commit https://github.com/quattor/template-library-grid/commit/bdcc6de3e8f86cda14a597b053a282ca582c6d61, however a recent commit removed the fix. I fix this issue.
