### ISSUE TITLE
Missing symbolic link

### ISSUE THREAD

**Issue by jas01** [quattor/template-library-grid#183]
They are a missing link or a misconfigure file inside the bdii configuration.

The configuration file

    /etc/bdii/gip/lcg-info-dynamic-scheduler-pbs.conf

claim

    [Main]
    static_ldif_file: /var/glite/static-file-all-CE-pbs.ldif
    static_glue2_ldif_file_computingshare: /var/glite/ComputingShare.ldif

but the file

    /var/glite/ComputingShare.ldif

are in fact in

    /var/lib/bdii/gip/ldif/ComputingShare.ldif

So either the configuration file need to change or quattor need to put a symbolic link between those two file

Without this the publication failed....silently.

**Comment by Pansanel** [comment]
It seems that you are using a old version of the templates. ```static_ldif_file``` is defined as:
```
GIP_LDIF_DIR + "/static-file-all-CE-"+lrms+".ldif
```
And ```GIP_LDIF_DIR``` is defined in  ```cfg/grid/umd-3/features/gip/env.pan``` as :
```
/var/lib/bdii/gip/ldif
```
