### ISSUE TITLE
condor_submit fails with SMPgranularity parameter

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-grid#194]
I have configured a CREAM-CE with htcondor batch system. 

When I include the variable:
SMPgranularity = $CORES;
in my JDL code, I get from CREAM an error of the condor_submit script 
 05 May 2017 16:25:35,580 INFO  AbstractJobExecutor             - JOB CREAM389568339 STATUS CHANGED: PENDING => ABORTED [description=submission to BLAH failed [retry count=3]] [failureReason=BLAH error: submission command failed (exit code = 1) (stdout:Usage: /usr/libexec/condor_submit.sh -c <command> [-i <stdin>] [-o <stdout>] [-e <stderr>] [-v <environment>] [-s <yes | no>] [-- command_arguments]-) (stderr:/usr/libexec/condor_submit.sh: illegal option -- S-) N/A (jobId = CREAM389568339)] [localUser=atl124]

the same JDL works when removing that parameter. 
The CONDOR_CONFIG ['multicore'] is set to true. 

The JDL:
[
Executable="$script_file";
InputSandbox = {"$script_file"};
StdOutput = "stdout.out";
StdError = "stderr.out";
OutputSandbox = {"stdout.out", "stderr.out"};
#SMPgranularity = $CORES;
CpuNumber = $CORES;
OutputSandboxBaseDestURI= "gsiftp://localhost";
]

**Comment by guillaume-philippon** [comment]
Hi,

It s a bug on blah parser. I ve done a PR (https://github.com/prelz/BLAH/pull/7) which was merged but apparently not available yet.

REgards

**Comment by almumontiel** [comment]
great!
thanks for sharing so quickly.
