### ISSUE TITLE
template personality/cream_ce/templates/cream-config.templ

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-grid#199]
JOB_SUBMISSION_MANAGER_SCRIPT_PATH should take /etc/glite-ce-cream-ce-utils/glite_cream_load_monitor.conf instead of  /etc/glite-ce-cream-utils/glite_cream_load_monitor.conf, because of the configuration in personality/cream_ce/monitor.pan which is using hard-coded path to  /etc/glite-ce-cream-ce-utils/glite_cream_load_monitor.conf

**Comment by Pansanel** [comment]
Does the last version of https://github.com/quattor/template-library-grid/blob/umd-3/personality/cream_ce/monitor.pan fix your issue?

**Comment by almumontiel** [comment]
thanks for the quick answer.
Yes it does.
Sorry, I didnt check that out before submitting the issue.
Let me close it.

**Comment by Pansanel** [comment]
When I have pushed the code, I checked how to include a variable in a prefix. It seems not to be supported actually. It would be much more cleaner.

**Comment by jrha** [comment]
Variables in a `prefix` are not supported, but the PR I just opened should solve your problem.

**Comment by stdweird** [comment]
fyi `prefix` is a preprocessor statement, not part of the any evaluated dml.
