### ISSUE TITLE
htcondor repo

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-grid#204]
template template-library-grid/repository/config/htcondor.pan
Currently the repository defined by HTCONDOR_YUM_REPOSITORY_NAME is not being used. According to line 64:

variable YUM_HTCONDOR_REPOSITORY_LIST ?= {
  if ( !is_null(YUM_HTCONDOR_REPOSITORY_LIST) ) {
    **append('htcondor');**
  };
};

only 'htcondor' is appended.
Shouldn't it be append(HTCONDOR_YUM_REPOSITORY_NAME);  instead?

Cheers

**Comment by jrha** [comment]
I think so, yes.
