### ISSUE TITLE
features/htcondor/server/groups: voms-clients package renamed

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-grid#214]
The package voms-clients3 is included. But the new UMD 4 repo updates it to use voms-clients-java instead. 
I follow couple of references (issues) regarding this:
https://issues.infn.it/jira/browse/CREAM-186
https://ggus.eu/index.php?mode=ticket_info&ticket_id=136074

**Comment by jouvin** [comment]
@almumontiel I think it is a well known issue but I was not directly involved in fixing it andI don't know if the fix we did at GRIF was upstreamed... @sartiran @guillaume-philippon or @victor-mendoza may know but I don't know if they are here these days (I know that @guillaume-philippon is in vacation until mid-august).

**Comment by sartiran** [comment]
Hi,

the fix we have at GRIF (adding a variable to allow changing the name of the voms package to include) was not upstreamed indeed. If you want, I can make a PR with this plus other recent changes.

Regards,
Andrea

**Comment by jrha** [comment]
Yes please!

**Comment by sartiran** [comment]
OK. There are quite some changes that have running in prod since a while here at GRIF and have never been upstreamed to the quattor repository. I'm preparing a PR (but it may take some time).

**Comment by jrha** [comment]
Many thanks

**Comment by sartiran** [comment]
PR done https://github.com/quattor/template-library-grid/pull/215
