### ISSUE TITLE
collisions group id

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-grid#226]
On a fresh install with centos7 (7.6.1810)  which uses the uses infosys and edginfo users, I find collisions in the groupid.

[INFO] running component: accounts
---------------------------------------------------------
[INFO] System has 33 accounts in 57 groups
[WARN] No groups found for root in the system. Assigning default ones: root, adm, bin, daemon, sys, disk
[INFO] Changing gid of group nagios to 76389
[ERROR] Collision found between groups ssh_keys and infosys for id 997
[ERROR] Collision found between groups edginfo and input for id 999
[ERROR] System would be inconsistent. Leaving without changing anything
[INFO] configure on component accounts executed, 3 errors, 1 warnings
[INFO] EVENT: accounts modified file /etc/login.defs

**Comment by jrha** [comment]
This is fixable, but would changing the UIDs of templated accounts harm existing installs?
