### ISSUE TITLE
14.6.0: WMS without a LB not working

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-grid#86]
Templates for WMS in 14.6.0 works only with a WMS/LB configuration. A WMS only machine fails to register jobs because it fails to communicate with the LB. Looks like there are some missing services.

**Comment by Pansanel** [comment]
@jouvin : may we close this bug? WMS should be decommissioned this year and probably that nobody will fix this issue.

**Comment by Pansanel** [comment]
For your information, WMS should be decommissioned at the end of 2017.

**Comment by jrha** [comment]
@jouvin Due to decommissioning of the WMS by the end of this year I am marking this as won't fix and closing it, if you still feel that it needs fixing, please feel free to re-open it.
